config: &config
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

credentials: &credentials
  host:     <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || ENV['PG_HOST'] || "localhost" %>
  port:     <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || ENV['PG_PORT'] %>
  username: <%= ENV['PG_USER'] || "croissant" %>

development:
  <<: *config
  <<: *credentials
  database: croissant_development

test:
  <<: *config
  <<: *credentials
  database: croissant_test

production:
  <<: *config
  url: <%= ENV['DATABASE_URL'] %>
