default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  user: croissant
  database: croissant_development

test:
  <<: *default
  user: croissant
  database: croissant_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
